### ISSUE TITLE
Replaying audio

### ISSUE THREAD

**Issue by scottgarner** [mohayonao/timbre.js#42]
I'm sure I'm missing something super obvious, but what do I need to do to keep replaying a sound? This only plays once.

```
var T = require("timbre");
var audio_src = T("audio", {}).loadthis("cicada_2.wav");
setInterval(function(){
	console.log("trigger");
	audio_src.play();
}, 2000);
```

Really what I need is some kind of sampler where I can load and trigger a bunch of clips as needed. Maybe I'm missing that, too?

Thanks!

**Comment by mohayonao** [comment]
Sorry, I am no longer using timbre.js.
If my memory is correct, the below code maybe replay repeatedly.

```js
var T = require("timbre");
var audio_src = T("audio", {}).loadthis("cicada_2.wav");
setInterval(function(){
    console.log("trigger");
    audio_src.clone().play().on("ended", function() {
      this.pause();
    });
}, 2000);
```

**Comment by scottgarner** [comment]
Thank you for the quick response!

So timbre isn't really supported anymore? I wonder if you have any other suggestions for node.js audio modules that can easily trigger samples.

**Comment by jbielick** [comment]
The WebAudio API has most of the convenience and feature you're probably looking for.
There's a number of great [tutorials](http://www.html5rocks.com/en/tutorials/webaudio/intro/).

I wrote a very simple wrapper on top of the audio api in order to do what you're talking about. It's called [groove.js](https://github.com/jbielick/Groove.js). It's not as fleshed-out as you'll probably want it to be, but it got me started on building [this project](http://beets.joshbielick.com).

**Comment by scottgarner** [comment]
Thank you for the suggestion, @jbielick.

I'm working in node.js and was drawn to timbre.js because it works with the speaker module. I do see that there is a web audio module for node, though, so maybe that's the better direction.

**Comment by jbielick** [comment]
ah, interesting. I hadn't gotten to that point yet, but I'm also interested in building / sequencing the patterns built in the browser on the server side so they can be written to file (wav). Let me know what you find if don't mind!

**Comment by scottgarner** [comment]
I think I'm going to stick with timbre for my current prototype now that I have sounds triggering. I'll keep an eye out for other options.

**Comment by takosuke** [comment]
So has timbre become redundant because of the web audio api?That's a pity, I really liked this project. Keep up the good work!
