### ISSUE TITLE
error with npm install

### ISSUE THREAD

**Issue by maruilian11** [mohayonao/timbre.js#50]
when i use `npm install timbre`
it appear following error message

``` >
CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
../deps/mpg123/src/output/alsa.c:19:28: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>
                            ^
compilation terminated.
```

(i have tried to install other lib, and it run successfully.)
is there anything i miss?

**Comment by mohayonao** [comment]
timbre.js uses ALSA (node-speaker) for Node.js support.

Please see the document of `node-speaker`: 
- https://github.com/TooTallNate/node-speaker

**Comment by mingfang** [comment]
if you're on ubuntu then you can try `apt-get install libasound2-dev`

**Comment by maruilian11** [comment]
thank you guys, i install them successfully!
